### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Failed to parse changedFields

### ISSUE THREAD

**Issue by itovarba** [pozil/pub-sub-api-node-client#11]
Hi, 

I'm facing issues with the client.js, when is trying to change from HexToBin an error message is launched indicating 'bin.replaceAll is not a function'. I.E: bin = bin.replaceAll("0", "0000");

I'm working with the latest version 2.4.0 available.

Thanks,
Iosu.

**Comment by pozil** [comment]
Hi @itovarba, I managed to find a fix to the parsing of changed fields. Can you try the latest release v2.4.1?
Let me know if this doesn't address your issue and I can reopen this.

**Comment by itovarba** [comment]
Thanks @pozil, It's working. Also I've been realized that I wasn't working with the latest node version.
